# NUMPY
NUMerical PYthon
- Fue creada para calculos matematicos
- Util para redes neuronales
- Te ayuda a optimizar memoria


In [1]:
import numpy as np 

# Array

Los np.arrays pueden ser de diferentes dimensiones
- VECTORES 1D (1D = array ([7,2,9,10]))
- MATRICES 2D (1D = array ([[5.2,3.0,4.5] , [9.1,0.1,0.3]]))
- TENSORES 3D (3D = array ( [[1,2] , [4,3] , [7,4]]  [[la segunda dimension]] )) usado para procesamiento de imagenes

# Arrays

In [4]:
list1 =  np.array (range(10))  #array de numpy, equivale a la serie, tienen diferentes foramtos
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np_cero = np.zeros(10, dtype=int) #array de ceros de 10 elementos, le aclaro el tipo de dato
np_cero

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np_unos = np.ones(10)
np_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np_relleno = np.full(10,256) #le paso un numero especifico
np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [10]:
np_random_dimensiones = np.random.randint(10, size = (3,4)) #10: hasta que valor , (3,4) 3 filas y 4 columnaqs
np_random_dimensiones

array([[9, 2, 8, 2],
       [2, 2, 2, 8],
       [4, 0, 6, 0]])

In [11]:
np_random_dimensiones.dtype


dtype('int32')

In [13]:
x = np_random_dimensiones.astype('f') #castea dato a flotante
x

array([[9., 2., 8., 2.],
       [2., 2., 2., 8.],
       [4., 0., 6., 0.]], dtype=float32)

In [17]:
np_random_dimensiones.ndim #te dice la cantidad de dimensiones (arranca desde 0, osea que son 3)

2

In [18]:
np_random_dimensiones.shape #te dice la dimensionalidad (cuantas filas y columnas tiene)

(3, 4)

In [19]:
np_random_dimensiones.size #tamanio = filas por columnas

12

In [21]:
np_random_dimensiones.itemsize #para saber el espacio que ocupa en memoria

4

In [22]:
np_random_dimensiones.nbytes #para saber el tamanio en bytes que ocupa en memoria

48

### ACCESO a los datos del array

In [29]:
rango = range(0,11)
Np_diez_numeros = np.array(rango)
Np_diez_numeros

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
Np_diez_numeros[0]
Np_diez_numeros[-2] #empezando de atras
#si es de 2 dimensiones tengo que especificar la fila y la columna xc [1,3]
Np_diez_numeros[:4] #todo hasta la dimension 4
Np_diez_numeros[3:] #desde el 3 en adelante
Np_diez_numeros[4:7] #desde el 4 al 7
Np_diez_numeros[::2] #todo de principoio a fin pero de dos en dos
Np_diez_numeros[::-2] #todo de atras para adelnate de dos en dos

array([10,  8,  6,  4,  2,  0])

# Manipulacion de datos

RESHAPE

In [15]:
import numpy as np
np.arange (1,65)
ajedrez = np.arange(1,65).reshape(8,8) #moldear
ajedrez


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

CONCATENACION

In [16]:
a1 = np.array([1,2,3])
a2 = np.array ([4,5,6])

arrays_concatenados = np.concatenate([a1,a2])
arrays_concatenados

array([1, 2, 3, 4, 5, 6])

In [17]:
arrays_apilados_v = np.vstack([a1,a2])
arrays_apilados_v



array([[1, 2, 3],
       [4, 5, 6]])

In [18]:

arrays_apilados_h = np.hstack([a1,a2])
arrays_apilados_h



array([1, 2, 3, 4, 5, 6])

In [24]:
array_partido = np.split(arrays_concatenados, [2,4]) #le doy lugares de corte, en tres partes 
array_partido

Parte1, Parte2, Parte3 = array_partido
array_partido

[array([1, 2]), array([3, 4]), array([5, 6])]

In [25]:
ajedrez_partido = np.hsplit (ajedrez, [2]) #dos arrays
ajedrez_partido

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26],
        [33, 34],
        [41, 42],
        [49, 50],
        [57, 58]]),
 array([[ 3,  4,  5,  6,  7,  8],
        [11, 12, 13, 14, 15, 16],
        [19, 20, 21, 22, 23, 24],
        [27, 28, 29, 30, 31, 32],
        [35, 36, 37, 38, 39, 40],
        [43, 44, 45, 46, 47, 48],
        [51, 52, 53, 54, 55, 56],
        [59, 60, 61, 62, 63, 64]])]

In [26]:
ajedrez_partido = np.vsplit (ajedrez, [4]) #dos arrays
ajedrez_partido

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

# Agregaciones